
# Generated by CodiumAI
from src import Arrow
from src import Bow
from src.Physic.Model import PhysicModel


import pytest

class TestPhysicModel:
    # Tests that the shooting method returns a list of 3 elements when given valid input parameters
    def test_shooting_with_valid_input(self):
        arrow = Arrow()
        bow = Bow(45)
        physic_model = PhysicModel(arrow, bow)
        result = physic_model.shooting(0, 0)
        assert isinstance(result, list)
        assert len(result) == 3

